image: python
violations:
  pep8: pep8 . --exclude='*migrations*,*settings*,*components*,*docs*'
  sloccount: sloccount .
  py_unittest:
    command: coverage run manage.py test violations projects tasks services coviolations_web push nodes
    stderr: true
  coverage:
    command: coverage report
    wait: py_unittest
  pip_review:
    command: pip-review
    nofail: true
deploy:
  master: fab update_production
  _: fab update_dev:{branch}
