language: python
python:
  - "2.7"
services:
  - mongodb
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
  - npm install -g bower
  - pip install fabric
  - fab install:ci
script:
  - coverage run manage.py test violations projects tasks services app push 2>test_out
after_script:
  - coverage report
  - coveralls
  - covio
