language: python
python:
  - "2.7"
services:
  - mongodb
  - redis-server
install:
  - npm install -g bower
  - pip install -U -r requirements/ci.txt
  - cp coviolations_web/settings/local_ci.py coviolations_web/settings/local.py
script:
  - coverage run manage.py test violations projects tasks services app
after_success:
  - coverage report
  - coveralls
  - covio
