language: python
python:
  - "2.7"
services:
  - mongodb
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
  - npm install -g bower
  - pip install -U -r requirements/ci.txt
  - cp coviolations_web/settings/local_ci.py coviolations_web/settings/local.py
script:
  - coverage run manage.py test violations projects tasks services app 2>test_out
after_script:
  - coverage report
  - coveralls
  - covio
