language: python
python:
  - "2.7"
services:
  - mongodb
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install -g bower
  - pip install fabric
  - cp coviolations_web/settings/local_ci.py coviolations_web/settings/local.py
  - fab install:ci
script:
  - coverage run manage.py test violations projects tasks services coviolations_web push 2>test_out
after_script:
  - coverage report
  - coveralls
  - covio
